### ISSUE TITLE
db:migrate command error

### ISSUE THREAD

**Issue by espinozaguillermo** [genieacs/genieacs-gui#101]
Hi,

when I run the command

`bin/rake db:migrate RAILS_ENV=development`

I receive the following error:

** Running via Spring preloader in process 22
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateUsers < ActiveRecord::Migration[4.2]
/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/migration.rb:528:in `inherited'
/opt/genieacs-gui/db/migrate/20160202145722_create_users.rb:1:in `<top (required)>'
/usr/local/bundle/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
/usr/local/bundle/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
/usr/local/bundle/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/migration.rb:986:in `load_migration'
/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/migration.rb:982:in `migration'
/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/migration.rb:977:in `disable_ddl_transaction'
/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/migration.rb:1350:in `use_transaction?'
/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/migration.rb:1342:in `ddl_transaction'
/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/migration.rb:1262:in `each'
/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/migration.rb:1212:in `migrate'
/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/migration.rb:1036:in `up'
/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/migration.rb:1011:in `migrate'
/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `load'
/usr/local/bundle/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `block in load'
/usr/local/bundle/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `load'
-e:1:in `<main>' **

I understand the error is because of the versions of project dependencies.
Is there any solution?
Thanks

**Comment by Malto4** [comment]
You have to modify the files in **/opt/genieacs-gui/db/migrate/**
In all of the files in that folder you need to change:

_class CreateUserRoles < ActiveRecord::Migration_

to

_class CreateUserRoles < ActiveRecord::Migration[4.2]_

Once you have done that try doing the migrate command again and it should work

**Comment by GLENDIS** [comment]
Hello,

I have a similar problem. Now modify the files in the route they indicate. But I run the command 
_bin / rails db: migrate RAILS_ENV = development_ 
and it gives me the following error:: 

SyntaxError: /opt/genieacs-gui/db/migrate/20160202145722_create_users.rb:1: syntax error, unexpected [, expecting ';' or '\n'
class CreateUsers <ActiveRecord :: Migration [ 5.2 ] ............................

Could you help me.

This is what is installed:
Red Hat 7.6

# ruby ​​-v 
  ruby 2.3.1p112 

# nodejs --version 
   v8.11.4 

# rails --version 
   Rails 5.2.1 

# mongo --version 
  v3.4.19

# redis-server --version
  Redis server v=5.0.3



![img3](https://user-images.githubusercontent.com/47321714/52879468-f41fc680-313d-11e9-84b3-daecb9e25c1c.png)

**Comment by moita69** [comment]
Changing all occurrences of "ActiveRecord::Migration" to "ActiveRecord::Migration[5.2]", then bin/rails "db:migrate RAILS_ENV=development", really makes the job
